main : cart.o bank.o functions.o main.o 
	g++ -g cart.o bank.o functions.o main.o

main.o : main.cpp
	g++ -c main.cpp -g

cart.o : cart.cpp
	g++ -c cart.cpp -g

bank.o : bank.cpp
	g++ -c bank.cpp -g

functions.o : functions.cpp
	g++ -c functions.cpp -g