source : main.o source1.o source2.o source3.o 
	gcc -g source1.o source2.o source3.o main.o

main.o : main.c
	gcc -c main.c -g

source1.o : source1.c
	gcc -c source1.c -g

source2.o : source2.c
	gcc -c source2.c -g

source3.o : source3.c
	gcc -c source3.c -g